- hosts: all
  become: true
  become_user: root
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum -y update && yum install -y python) || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup: # aka gather_facts
  roles:
    - host-setup

  tasks:
  - name: Download & unarchive CockroachDB
    unarchive:
      src: "https://binaries.cockroachdb.com/{{ crdb_package }}.tgz"
      dest: "{{ ansible_env.HOME }}"
      remote_src: true

  - name: Copy CockroachDB binany
    copy:
      src: "{{ ansible_env.HOME }}/{{ crdb_package }}/cockroach"
      dest: /usr/bin/cockroach
      owner: "{{ target_user }}"
      mode: u+rwx,g-wx,o-wx
      remote_src: true

  - name: Clean CockrochDB archive
    file:
      path: "{{ ansible_env.HOME }}/{{ crdb_package }}"
      state: absent
