---
- name: install essentials
  apt:
    update_cache: True
    name: "{{ packages }}"
  vars:
    packages:
      - gnupg
      - ethtool

- include_tasks: cluster.yml
  when: "not 'scylla-monitor' in group_names"

- include_tasks: monitor.yml
  when: "'scylla-monitor' in group_names"
