---
scylla_has_ssd: "{{ not(
      (scylla_ssd_disk is undefined)
      or
      (scylla_ssd_disk is none)
      or
      (scylla_ssd_disk | trim == '')
    ) }}"
scylla_develop_mode: "{{ scylla_has_ssd }}"
scylla_monitor_dir: "/tmp/scylla-monitor-{{ scylla_monitor_ver }}"
